In [1]:
import pandas as pd
import numpy as np
import cv2

convert image into numpy array 1 d

In [2]:
x=cv2.imread("NITIKA 1.jpg")

In [3]:
x.ravel()

array([184, 174, 150, ...,  73,  67,  60], dtype=uint8)

In [4]:
list1=["DIVYA 3.jpg","DIVYA 4.jpg","DIVYA 5.jpg","DIVYA.jpg","JITENDER 2.jpg","JITENDER 3.jpg","JITENDER 4.jpg","JITENDER 5.jpg","KESHAV 1.jpg","KESHAV 2.jpg","KESHAV 3.jpg","KESHAV 4.jpg","KESHAV 5.jpg","KESHAV 6.jpg","LIB MAM 1.jpg","LIB MAM 2.jpg","LIB MAM 4.jpg","LIB MAM 5.jpg","LIB MAM 6.jpg","LIB MAM 7.jpg","LIB MAM 8.jpg","MAHI 1.jpg","MAHI 2.jpg","MAHI 3.jpg","MAHI 4.jpg","MAHI 5.jpg","NITIKA 1.jpg","NITIKA 2.jpg","NITIKA 3.jpg","NITIKA 4.jpg","NITIKA 5.jpg"]
list2=[]

In [5]:
#now make all images like that 

In [6]:
import numpy as np
from PIL import Image
import os
import cv2

def create_2d_array_from_images(image_list, target_size=(512, 512)):
   
    all_1d_arrays = []

    for image_path in image_list:
        try:
            # 1. Open the image
            img = Image.open(image_path)
            

            # 2. Resize the image to a consistent size
            # This is the most crucial step to prevent errors!
            img_resized = img.resize(target_size)

            # 3. Convert the resized image to a NumPy array
            img_array = np.array(img_resized)

            # 4. Flatten the array into a single 1D array
            flattened_array = img_array.flatten()

            # Add the 1D array to our list
            all_1d_arrays.append(flattened_array)

        except Exception as e:
            print(f"Skipping image {image_path} due to an error: {e}")

    # 5. Stack all 1D arrays into a single 2D array
    # This works because all arrays in the list are now the same size
    if all_1d_arrays:
        return np.array(all_1d_arrays)
    else:
        return np.array([]) # Return an empty array if no images were processed


# Create the final 2D array
final_2d_array = create_2d_array_from_images(list1,(512,512))


   
   
    
    
    
    

In [7]:
print(final_2d_array)

[[163 177 186 ...  59  72  77]
 [160 171 177 ...  65  65  67]
 [154 175 178 ...  54  69  76]
 ...
 [151 178 185 ...  62  65  75]
 [162 176 185 ...  65  65  77]
 [157 178 181 ...  44  49  53]]


In [8]:

image_labels = [0,0,0,0,2,2,2,2,3,3,3,3,3,3,5,5,5,5,5,5,5,4,4,4,4,4,1,1,1,1,1] 

# Convert the list to a NumPy array.
labels_np = np.array(image_labels)
labels_2d = labels_np.reshape(-1, 1)
# You now have both your image data and corresponding labels ready for training.
print("Shape of labels array:", labels_2d.shape)
print("Labels:", labels_2d)


Shape of labels array: (31, 1)
Labels: [[0]
 [0]
 [0]
 [0]
 [2]
 [2]
 [2]
 [2]
 [3]
 [3]
 [3]
 [3]
 [3]
 [3]
 [5]
 [5]
 [5]
 [5]
 [5]
 [5]
 [5]
 [4]
 [4]
 [4]
 [4]
 [4]
 [1]
 [1]
 [1]
 [1]
 [1]]


splitting the data

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x=final_2d_array

In [11]:
x.shape

(31, 786432)

In [12]:
y=labels_2d

In [13]:
y.shape

(31, 1)

In [14]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2)

In [15]:
train_x

array([[113, 129, 133, ...,  13,  12,  17],
       [181, 179, 166, ...,  99,  95,  68],
       [240, 251, 211, ..., 106,  91,  87],
       ...,
       [152, 175, 187, ...,  60,  67,  72],
       [111, 129, 129, ...,  17,  17,  19],
       [113, 126, 134, ...,  16,  17,  21]], dtype=uint8)

In [16]:
train_y

array([[5],
       [4],
       [2],
       [4],
       [2],
       [5],
       [5],
       [4],
       [3],
       [0],
       [3],
       [1],
       [3],
       [3],
       [5],
       [3],
       [4],
       [3],
       [0],
       [2],
       [1],
       [1],
       [5],
       [5]])

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
model=LogisticRegression()

In [19]:
model.fit(train_x,train_y)

C:\Users\Nitika\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [29]:
a=model.predict(test_x[0:1])

In [43]:
a=int(input("enter first value"))
b=int(input("enter 2 value"))
y=model.predict(test_x[a:b:-1])
for i in range(len(y)):
    if y[i]==0:
        print("DIVYA")
    elif y[i]==1:
        print("nitika")
        
    elif y[i]==2:
        print("JITENDER")
    elif y[i]==3:
        print("Keshav")
    elif y[i]==4:
        print("MAHI")
    elif y[i]==5:
        print("LIB MAM")
    else:
        print("OTHERS")




enter first value -2
enter 2 value -3


MAHI


In [28]:
model.score(train_x,train_y)

1.0

In [40]:
a=[1,2,3,4,5]
print(a[-2:-3:-1])

[4]
